// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using test2.DatabaseContext;

namespace test2.Migrations
{
    [DbContext(typeof(LockerDbContext))]
    partial class LockerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065");

            modelBuilder.Entity("test2.DatabaseContext.Models.Account", b =>
                {
                    b.Property<string>("Id_account")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("ExpoToken");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<int>("Point");

                    b.Property<string>("Role");

                    b.Property<string>("Token");

                    b.HasKey("Id_account");

                    b.ToTable("accounts");
                });

            modelBuilder.Entity("test2.DatabaseContext.Models.Content", b =>
                {
                    b.Property<int>("Id_content")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsActive");

                    b.Property<string>("PlainText");

                    b.HasKey("Id_content");

                    b.ToTable("contents");
                });

            modelBuilder.Entity("test2.DatabaseContext.Models.LockerMetadata", b =>
                {
                    b.Property<string>("Mac_address")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsActive");

                    b.Property<string>("Location");

                    b.HasKey("Mac_address");

                    b.ToTable("lockerMetadatas");
                });

            modelBuilder.Entity("test2.DatabaseContext.Models.Notification", b =>
                {
                    b.Property<int>("Id_notification")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Id_account");

                    b.Property<int>("Id_content");

                    b.Property<int>("Id_reserve");

                    b.Property<bool>("IsShow");

                    b.Property<bool>("Read");

                    b.HasKey("Id_notification");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("test2.DatabaseContext.Models.Reservation", b =>
                {
                    b.Property<int>("Id_reserve")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<DateTime>("DateModified");

                    b.Property<DateTime>("EndDay");

                    b.Property<string>("Id_account");

                    b.Property<int>("Id_vacancy");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Location");

                    b.Property<string>("Size");

                    b.Property<DateTime>("StartDay");

                    b.Property<string>("Status");

                    b.HasKey("Id_reserve");

                    b.ToTable("reservations");
                });

            modelBuilder.Entity("test2.DatabaseContext.Models.Vacancy", b =>
                {
                    b.Property<int>("Id_vacancy")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsActive");

                    b.Property<string>("Mac_address");

                    b.Property<string>("No_vacancy");

                    b.Property<string>("Size");

                    b.HasKey("Id_vacancy");

                    b.ToTable("vacancies");
                });
#pragma warning restore 612, 618
        }
    }
}
